# Generated by Django 6.0.2 on 2026-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreport',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='h1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='missing_alt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
