# Generated by Django 6.0.2 on 2026-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_seoreport_status_alter_seoreport_h1_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreport',
            name='pages_crawled',
            field=models.IntegerField(default=0),
        ),
    ]
