# Generated by Django 6.0.2 on 2026-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_seoreport_pages_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreport',
            name='has_csp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoreport',
            name='has_hsts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoreport',
            name='has_x_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoreport',
            name='robots_txt_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoreport',
            name='sitemap_found',
            field=models.BooleanField(default=False),
        ),
    ]
