# Generated by Django 6.0.2 on 2026-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_seoreport_has_csp_seoreport_has_hsts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreport',
            name='crawl_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
