# Generated by Django 6.0.2 on 2026-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_seoreport_crawl_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreport',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
