# Generated by Django 6.0.2 on 2026-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_seoreport_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="seoreport",
            name="screenshot",
            field=models.TextField(blank=True, null=True),
        ),
    ]
