# Generated by Django 6.0.2 on 2026-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_seoreport_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="seoreport",
            name="suggestions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
